### ISSUE TITLE
出现报错无法使用

### ISSUE THREAD

**Issue by Nuctori** [Tencent/LuaHelper#192]
`goroutine 694 [running]:
luahelper-lsp/langserver/check/common.(*DirManager).GetAllCompleFile(0xc000028240, {0xc0001f9230, 0x3}, 0x4, 0x0, 0xc000f8d018)
	I:/companyproject/LuaHelper/github/LuaHelper/luahelper-lsp/langserver/check/common/dir_manager.go:478 +0x7db
luahelper-lsp/langserver/check.(*AllProject).CodeCompleteFile(0xc00025e8c0, {0xc0072d2ac0?, 0x1486c90?}, {0x13f1b00, 0x7}, 0x4, {0xc0072d2ae2, 0x18})
	I:/companyproject/LuaHelper/github/LuaHelper/luahelper-lsp/langserver/check/check_lsp_complete.go:32 +0x166
luahelper-lsp/langserver.(*LspServer).judgeCompeleteFile(0xc000156280, {0xc007231f80, 0x57}, {0xc0061724e0?, 0x182?, 0x1a0?}, 0x3a?)
	I:/companyproject/LuaHelper/github/LuaHelper/luahelper-lsp/langserver/textdocument_complete.go:365 +0x613
luahelper-lsp/langserver.(*LspServer).TextDocumentComplete(0xc000156280, {0x148cc58, 0xc007306180}, {{0x3ff0000000000000, {0x0, 0x0}}, {{{0xc0013b2b60, 0x61}}, {0x0, 0x3a}}, ...})
	I:/companyproject/LuaHelper/github/LuaHelper/luahelper-lsp/langserver/textdocument_complete.go:74 +0x651
reflect.Value.call({0x138c720?, 0xc0000524e0?, 0x136ec60?}, {0x13f0b68, 0x4}, {0xc007306360, 0x2, 0xc007306360?})
	D:/Go20/src/reflect/value.go:586 +0xb07
reflect.Value.Call({0x138c720?, 0xc0000524e0?, 0xffdfc7?}, {0xc007306360?, 0x2?, 0x1?})
	D:/Go20/src/reflect/value.go:370 +0xbc
github.com/yinfei8/jrpc2/handler.newHandler.func8({0x148cc58?, 0xc007306180}, 0x17159f8?)
	D:/Go20/gopath/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/handler/handler.go:240 +0x208
github.com/yinfei8/jrpc2/handler.Func.Handle(0xc000060640?, {0x148cc58?, 0xc007306180?}, 0x1?)
	D:/Go20/gopath/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/handler/handler.go:23 +0x2f
github.com/yinfei8/jrpc2.(*Server).invoke(0xc00016a000, {0x148cbb0?, 0xc004813590?}, {0x148abe0, 0xc000055600}, 0xc004c4fec0)
	D:/Go20/gopath/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/server.go:347 +0x166
github.com/yinfei8/jrpc2.(*Server).dispatch.func1.1()
	D:/Go20/gopath/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/server.go:229 +0xdd
created by github.com/yinfei8/jrpc2.(*Server).dispatch.func1
	D:/Go20/gopath/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/server.go:232 +0x17b
[Info  - 16:32:20] Connection to server got closed. Server will restart.
[Error - 16:32:20] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\connection.js:1061:27)
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-languageclient\lib\common\client.js:73:35)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-languageclient\lib\common\client.js:2474:42)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-languageclient\lib\node\main.js:159:15)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-languageclient\lib\common\client.js:2461:18)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\connection.js:260:26)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at StreamMessageReader.fireClose (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
	at Socket.<anonymous> (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\messageReader.js:125:42)
	at Socket.emit (node:events:525:35)
	at Pipe.<anonymous> (node:net:757:14)
panic: runtime error: slice bounds out of range [4:3]

goroutine 664 [running]:
luahelper-lsp/langserver/check/common.(*DirManager).GetAllCompleFile(0xc000028240, {0xc0001f9230, 0x3}, 0x4, 0x0, 0xc007655018)
	I:/companyproject/LuaHelper/github/LuaHelper/luahelper-lsp/langserver/check/common/dir_manager.go:478 +0x7db
luahelper-lsp/langserver/check.(*AllProject).CodeCompleteFile(0xc000578ee0, {0xc0027aea40?, 0x1486c90?}, {0x13f1b00, 0x7}, 0x4, {0xc0027aea62, 0x17})
	I:/companyproject/LuaHelper/github/LuaHelper/luahelper-lsp/langserver/check/check_lsp_complete.go:32 +0x166
luahelper-lsp/langserver.(*LspServer).judgeCompeleteFile(0xc0001660a0, {0xc00061cfc0, 0x57}, {0xc001fb3040?, 0x181?, 0x1a0?}, 0x39?)
	I:/companyproject/LuaHelper/github/LuaHelper/luahelper-lsp/langserver/textdocument_complete.go:365 +0x613
luahelper-lsp/langserver.(*LspServer).TextDocumentComplete(0xc0001660a0, {0x148cc58, 0xc004b711d0}, {{0x3ff0000000000000, {0x0, 0x0}}, {{{0xc0003144d0, 0x61}}, {0x0, 0x39}}, ...})
	I:/companyproject/LuaHelper/github/LuaHelper/luahelper-lsp/langserver/textdocument_complete.go:74 +0x651
reflect.Value.call({0x138c720?, 0xc0000524e0?, 0x136ec60?}, {0x13f0b68, 0x4}, {0xc004b71890, 0x2, 0xc004b71890?})
	D:/Go20/src/reflect/value.go:586 +0xb07
reflect.Value.Call({0x138c720?, 0xc0000524e0?, 0xffdfc7?}, {0xc004b71890?, 0x2?, 0x1?})
	D:/Go20/src/reflect/value.go:370 +0xbc
github.com/yinfei8/jrpc2/handler.newHandler.func8({0x148cc58?, 0xc004b711d0}, 0x17159f8?)
	D:/Go20/gopath/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/handler/handler.go:240 +0x208
github.com/yinfei8/jrpc2/handler.Func.Handle(0xc000060640?, {0x148cc58?, 0xc004b711d0?}, 0x1?)
	D:/Go20/gopath/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/handler/handler.go:23 +0x2f
github.com/yinfei8/jrpc2.(*Server).invoke(0xc00016a000, {0x148cbb0?, 0xc004c0a230?}, {0x148abe0, 0xc000055600}, 0xc007432140)
	D:/Go20/gopath/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/server.go:347 +0x166
github.com/yinfei8/jrpc2.(*Server).dispatch.func1.1()
	D:/Go20/gopath/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/server.go:229 +0xdd
created by github.com/yinfei8/jrpc2.(*Server).dispatch.func1
	D:/Go20/gopath/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/server.go:232 +0x17b
[Error - 16:32:33] Connection to server got closed. Server will not be restarted.
[Error - 16:32:33] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\connection.js:1061:27)
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-languageclient\lib\common\client.js:73:35)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-languageclient\lib\common\client.js:2474:42)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-languageclient\lib\node\main.js:159:15)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-languageclient\lib\common\client.js:2461:18)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\connection.js:260:26)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at StreamMessageReader.fireClose (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
	at Socket.<anonymous> (c:\Users\Administrator\.vscode\extensions\yinfei.luahelper-0.2.24\node_modules\vscode-jsonrpc\lib\common\messageReader.js:125:42)
	at Socket.emit (node:events:525:35)
	at Pipe.<anonymous> (node:net:757:14)`

**Comment by Nuctori** [comment]
我这边曾改变过项目的盘符，可能和这个有关
